# Generated by Django 4.2.15 on 2024-11-01 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_type', models.CharField(max_length=100)),
                ('reason_for_applying', models.TextField()),
                ('personal_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scholarship.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='GuardianInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian_name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=50)),
                ('guardian_phone', models.CharField(max_length=15)),
                ('guardian_email', models.EmailField(max_length=254)),
                ('guardian_address', models.TextField()),
                ('personal_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scholarship.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_statement', models.BooleanField()),
                ('applicant_declaration', models.BooleanField()),
                ('applicant_signature', models.CharField(max_length=100)),
                ('date_of_application', models.DateField(auto_now_add=True)),
                ('identification_document', models.FileField(upload_to='identification_document/')),
                ('passport_photo', models.ImageField(upload_to='passport_photo/')),
                ('personal_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scholarship.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=200)),
                ('course_of_study', models.CharField(max_length=200)),
                ('current_year', models.CharField(max_length=20)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('personal_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scholarship.personalinfo')),
            ],
        ),
    ]
